"""empty message

Revision ID: 9e594c2cb3a7
Revises: 
Create Date: 2024-02-16 19:58:57.141475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e594c2cb3a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Контроль заданий на выпуск продук')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Контроль заданий на выпуск продук',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Контроль заданий на выпуск про_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Контроль заданий на выпуск прод_pkey')
    )
    # ### end Alembic commands ###
